### ISSUE TITLE
Error when click on Accounting module

### ISSUE THREAD

**Issue by kittiu** [kittiu/aagc#3]
![Selection_246](https://user-images.githubusercontent.com/1973598/74703404-abfb1e80-523f-11ea-87b2-7184ea20353e.png)

![Selection_247](https://user-images.githubusercontent.com/1973598/74703408-af8ea580-523f-11ea-9ac8-b00f05afad42.png)

**Comment by kittiu** [comment]
Note: I did try to update "Analytic" module, but still has same error.

**Comment by AaronHForgeFlow** [comment]
@kittiu :fearful: The database I restored in the server had a module installed but is missing from the addons path in the server. I just uninstalled it. Hope this is the last module missing, I am checking. Apologies.

**Comment by kittiu** [comment]
Thank you!
