### ISSUE TITLE
Bug: Duplicated tab in Project

### ISSUE THREAD

**Issue by kittiu** [kittiu/aagc#7]
![Selection_251](https://user-images.githubusercontent.com/1973598/74709936-f639cb00-5252-11ea-9aca-4c4f0b2b7496.png)

**Comment by kittiu** [comment]
Then, I find 2 of them in the view,

![image](https://user-images.githubusercontent.com/1973598/74709982-1d909800-5253-11ea-9423-29195feecb12.png)

**Comment by AaronHForgeFlow** [comment]
Thanks for letting me know. Probably will remove the view from the module project_earned_value_task because it actually depends on the other.

**Comment by AaronHForgeFlow** [comment]
Solved now. Thanks for reporting @kittiu
