### ISSUE TITLE
Question: In Project Bids, what is "TRANSFER TO PROJECT" 

### ISSUE THREAD

**Issue by kittiu** [kittiu/aagc#8]
![image](https://user-images.githubusercontent.com/1973598/74711106-bb856200-5255-11ea-8d05-4463850ffb87.png)

**Comment by AaronHForgeFlow** [comment]
This will create planned analytic planning lines. They are used to capture the planned cost or
revenue. This will help later for reporting. In the "Work In Progress Statement" report we will be able to compare the planned costs and revenues respect to actual costs and actual revenues. That way we will be able to compare if we are close to the plan or not, so we can do changes in the project.
